# Data Preprocessing

> Read Review file & Book file

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_book = pd.read_csv("all_book.csv")
df_book

,Book_Name,Book_Author,Book_Category,Completion_Percent,ReadTogether,ReviewCount,Keyword,AudioBook
0,"어린 왕자, 후쿠시마 이후",변홍철,에세이,NaN,2개,0,NaN,X
1,경제지표를 읽는 시간,빈센트(김두언),경제경영,완독할 확률 49%,"1,300개",4개,경제입문,X
2,거대한 충격 이후의 세계,서영민,경제경영,완독할 확률 65%,378개,3개,NaN,X
3,노화의 재설계,모건 레빈 지음 / 이한음 옮김,인문,완독할 확률 43%,473개,3개,NaN,X
4,근대의 아틀리에,김영동,인문,NaN,9개,0,NaN,X
...,...,...,...,...,...,...,...,...
12711,다음 생엔 돌이 되고 싶다.,강다희,에세이,NaN,3개,0,NaN,X
12712,배터리 다이제스트 TOP9,선우 준,과학,NaN,5개,0,NaN,X
12713,배터리 다이제스트 TOP10,선우 준,과학,NaN,5개,0,NaN,X
12714,평신도 및 목회자를 위한 다니엘서 Q&A,우슬초,종교,NaN,3개,0,NaN,X
12715,나로 돌아가는 여행,곽나원,에세이,NaN,4개,0,NaN,X

In [3]:
df_review = pd.read_csv("all_review.csv")
df_review = df_review.drop(["Unnamed: 0", "Column1", "Column2", "Column3"], axis=1)
df_review[100:120]

,Nickname,Review_Text,Book_Name
100,꿈과함께성장한다,너무 재밌습니다 진솔한 이야기이고 부모님을 떠오르게 하는 책이에요,나의 이상하고 평범한 부동산 가족
101,그레이트토리,우연히 발견하고 단숨에 읽었네요. 우리 부모님은 어떤 역경을 딛고 살아오셨을까.....,나의 이상하고 평범한 부동산 가족
102,조심스러운 창의력 대장_959952,대한민국 주택 개발의 미시사. 부동산으로 흥하고 망한 한 가족의 이야기가 찡하게 와...,나의 이상하고 평범한 부동산 가족
103,예리한 명사_279044,차가운 현실에 얼얼하다가도\n마음이 먹먹해집니다,나의 이상하고 평범한 부동산 가족
104,어야둥기둥기,가볍게 읽기 시작했다가 후반부에 찡찡 울면서 봤네요 ㅎㅎㅎ잘 봤어요,나의 이상하고 평범한 부동산 가족
105,선선!,영화 <버블 패밀리> 제작노트 같은 느낌. 좋은 영화이니 함께 보시길 더욱 추천드려요.,나의 이상하고 평범한 부동산 가족
106,cooljun,은퇴준비에 도움이 될만한 내용이네요.,이것은 빠른 경제적 자유를 위한 책
107,제주바다,하느범더 읽어 볼게요,이것은 빠른 경제적 자유를 위한 책
108,vision215,재미있네요,이것은 빠른 경제적 자유를 위한 책
109,매력적인 이상형_622305,조기 은퇴가 가능한 것은 자신의 밥그릇 크기에 달려있다.,이것은 빠른 경제적 자유를 위한 책
110,허연깃발,"드라마 분량으론 1화 분량 입니다. 이후 분량은 없으며 ""유괴의 날"" 도서로 이어집니다.",유괴의 날 웹툰
111,매력적인 꿈쟁이_323716,다음 이야기 궁금하네요^^,유괴의 날 웹툰
112,빙구징구,재밌이이이있다,유괴의 날 웹툰
113,1041803,1권끝?\n없나요?,유괴의 날 웹툰
114,토리공원,재미쒀여 !!,유괴의 날 웹툰
115,보미오나봄,나오는 중인건가? 1화뿐인데요?,유괴의 날 웹툰
116,짱구맛나,몇 가지 가슴에 남는 문장이 있다,인생의 언어가 필요한 순간
117,코람데오 영적거장,신앙인들이 갖는 질문에도 큰 도움이 돠었어요 사서 또 읽고 싶네요,하나님 없이도 잘 살 수 있지 않나요?
118,hmg5613585,ENTP 눈물 없는자가 영화를 보며 너무 재미있어서 눈물이 난 영화 책으로 빨리 보...,엘리멘탈 그래픽노블(한글)
119,책책책책을읽자구우,불의 언어엔 디쇽 이란 말이 있어\n영원한 빛은 없으니 빛날 만끽하라 라는 뜻이야,엘리멘탈 그래픽노블(한글)

## Book Data Preprocessing

### Unnecessary Book_Category Removing
> Removing 'no', '미래북', '웅진지식하우스' etc...

In [4]:
df_book["Book_Category"].unique()

array(['에세이', '경제경영', '인문', '청소년', '외국어', '자기계발', '매거진', '여행', '밀리 오리지널',
       '오디오북', 'no', '소설', '미래북', '로맨스·BL', '어린이', '판타지·무협', '웅진지식하우스',
       '과학', '19금', 'IT', '사회', '철학', '종교', '라이프스타일', '부모', '콘택트',
       '세계문학전집', '지식과감성#', '챗북', '역사', '인디펍', '만화', '문학동네', '민음사', '좋은땅',
       '빨간펜 동화', '밀리의서재', '시공사', '디즈니', '빨간펜', '도서출판 선', '빛', '상재공간',
       '주식회사 이프로엔터테인먼트', '행성B', '리안', '젬마', '블래스트 출판', '노란돼지', '시대교육',
       '미디어숲', '메이트북스', '떠오름', '좋은습관연구소', '에이치비프레스', '달콤북스', '포레스트북스',
       '스토리텔러', '미래의창 주식회사', '반니', '동북아역사재단', '밀리의 서재', 'FIKA(피카)',
       '행복에너지', '씨네21북스', '문예출판사', '작가정신', '메이븐', '내인생의책', '모노(잡지)',
       '비타북스', '테마여행신문 TTN Theme Travel News Korea', '위니', '밀리', '푸른숲',
       '네오픽션', '천그루숲', '서해문집', '팬덤북스', '시대의창', '21세기북스', '성안당', '동녘',
       '걷는나무', '리더스북', '메디치미디어', '애플북스', '세종서적', '쌤앤파커스', '한겨레출판', '생각의길',
       '카시오페아', '미래의창', '북닻', '토네이도', '청아출판사', '흐름출판', '김영사', '유유',
       '을유문화사', '서랍의날씨', '봄날의책', nan], dtype=object)

In [5]:
# Check filtered "Book_Category" Data
keyword = "웅진지식하우스"
filtered_data = df_book[df_book['Book_Category'].str.contains(keyword, na=False, case=False)]

# Display the filtered data
filtered_data

,Book_Name,Book_Author,Book_Category,Completion_Percent,ReadTogether,ReviewCount,Keyword,AudioBook
101,워킹 데드 해방일지,사이몬 스톨조프,웅진지식하우스,완독할 확률 42%,283개,2개,NaN,X

In [6]:
categories_to_remove = ["no", "미래북", "웅진지식하우스", "콘택트", "지식과감성#", "인디펍", "문학동네", "민음사", "좋은땅", "빨간펜 동화", 
                        "시공사", "밀리의 서재", "빨간펜", "도서출판 선", "빛", "상재공간", "주식회사 이프로엔터테인먼트", "행성B", "리안", 
                        "젬마", "블래스트 출판", "노란돼지", "시대교육", "미디어숲", "메이트북스", "떠오름", "좋은습관연구소", "에이치비프레스", 
                        "달콤북스", "포레스트북스", "스토리텔러", "미래의창 주식회사", "반니", "동북아역사재단", "밀리의 서재", "FIKA(피카)", 
                        "행복에너지", "씨네21북스", "문예출판사", "작가정신", "메이븐", "내인생의책", "모노(잡지)", "비타북스", "테마여행신문 TTN Theme Travel News Korea", 
                        "위니", "밀리", "푸른숲", "네오픽션", '네오픽션', '천그루숲', '서해문집', '팬덤북스', '시대의창', '21세기북스', '성안당', '동녘', '걷는나무', 
                        '리더스북', '메디치미디어', '애플북스', '세종서적', '쌤앤파커스', '한겨레출판', '생각의길', '카시오페아', '미래의창', '북닻', '토네이도', '청아출판사', 
                        '흐름출판', '김영사', '유유', '을유문화사', '서랍의날씨', '봄날의책', '밀리의서재']

df_book = df_book[~df_book['Book_Category'].isin(categories_to_remove)]

df_book = df_book.dropna(subset=['Book_Category'])

df_book

,Book_Name,Book_Author,Book_Category,Completion_Percent,ReadTogether,ReviewCount,Keyword,AudioBook
0,"어린 왕자, 후쿠시마 이후",변홍철,에세이,NaN,2개,0,NaN,X
1,경제지표를 읽는 시간,빈센트(김두언),경제경영,완독할 확률 49%,"1,300개",4개,경제입문,X
2,거대한 충격 이후의 세계,서영민,경제경영,완독할 확률 65%,378개,3개,NaN,X
3,노화의 재설계,모건 레빈 지음 / 이한음 옮김,인문,완독할 확률 43%,473개,3개,NaN,X
4,근대의 아틀리에,김영동,인문,NaN,9개,0,NaN,X
...,...,...,...,...,...,...,...,...
12711,다음 생엔 돌이 되고 싶다.,강다희,에세이,NaN,3개,0,NaN,X
12712,배터리 다이제스트 TOP9,선우 준,과학,NaN,5개,0,NaN,X
12713,배터리 다이제스트 TOP10,선우 준,과학,NaN,5개,0,NaN,X
12714,평신도 및 목회자를 위한 다니엘서 Q&A,우슬초,종교,NaN,3개,0,NaN,X
12715,나로 돌아가는 여행,곽나원,에세이,NaN,4개,0,NaN,X

In [7]:
df_book["Book_Category"].unique()

array(['에세이', '경제경영', '인문', '청소년', '외국어', '자기계발', '매거진', '여행', '밀리 오리지널',
       '오디오북', '소설', '로맨스·BL', '어린이', '판타지·무협', '과학', '19금', 'IT', '사회',
       '철학', '종교', '라이프스타일', '부모', '세계문학전집', '챗북', '역사', '만화', '디즈니'],
      dtype=object)

### Delete Missing Value in "Book_Author"

In [8]:
#Check Missing Value in Book_Author
missing_authors = df_book[df_book['Book_Author'].isna()]

missing_authors

,Book_Name,Book_Author,Book_Category,Completion_Percent,ReadTogether,ReviewCount,Keyword,AudioBook
3235,김언호의 서재 탐험,NaN,오디오북,NaN,36개,0,NaN,X
3563,우리 아이에게 들려주는 엄마의 인형동화 - 늑대와 일곱마리 아기 염소,NaN,오디오북,NaN,2개,0,NaN,X
3723,엄마가 들려주고 싶은 동화 - 호랑이가 준 요술 보자기,NaN,오디오북,NaN,1개,0,NaN,X
4517,앵커 씨의 행복 이야기,NaN,오디오북,NaN,3개,0,NaN,X
4606,임금님 집에 예쁜옷을 입혀요,NaN,오디오북,NaN,1개,0,NaN,X
7060,미서비스 \n \n 스프린터,NaN,오디오북,NaN,576개,4개,NaN,X
7061,미서비스 \n \n 튤립 모양,NaN,오디오북,NaN,423개,1개,NaN,X
8544,서비스 종료 도서,NaN,19금,NaN,0개,0,NaN,X

In [9]:
# Delete Missing Value
df_book = df_book.dropna(subset=['Book_Author'])

df_book

,Book_Name,Book_Author,Book_Category,Completion_Percent,ReadTogether,ReviewCount,Keyword,AudioBook
0,"어린 왕자, 후쿠시마 이후",변홍철,에세이,NaN,2개,0,NaN,X
1,경제지표를 읽는 시간,빈센트(김두언),경제경영,완독할 확률 49%,"1,300개",4개,경제입문,X
2,거대한 충격 이후의 세계,서영민,경제경영,완독할 확률 65%,378개,3개,NaN,X
3,노화의 재설계,모건 레빈 지음 / 이한음 옮김,인문,완독할 확률 43%,473개,3개,NaN,X
4,근대의 아틀리에,김영동,인문,NaN,9개,0,NaN,X
...,...,...,...,...,...,...,...,...
12711,다음 생엔 돌이 되고 싶다.,강다희,에세이,NaN,3개,0,NaN,X
12712,배터리 다이제스트 TOP9,선우 준,과학,NaN,5개,0,NaN,X
12713,배터리 다이제스트 TOP10,선우 준,과학,NaN,5개,0,NaN,X
12714,평신도 및 목회자를 위한 다니엘서 Q&A,우슬초,종교,NaN,3개,0,NaN,X
12715,나로 돌아가는 여행,곽나원,에세이,NaN,4개,0,NaN,X

### Check Missing Value in "ReadTogether"
> ReadTogther means "like"

In [10]:
#Check Missing Value in Book_Author
missing_readtogether = df_book[df_book['ReadTogether'].isna()]

missing_readtogether

Empty DataFrame
Columns: [Book_Name, Book_Author, Book_Category, Completion_Percent, ReadTogether, ReviewCount, Keyword, AudioBook]
Index: []

### Check Data in "ReviewCount"

In [11]:
missing_reviewcount = df_book[df_book['ReviewCount'].isna()]

missing_reviewcount

Empty DataFrame
Columns: [Book_Name, Book_Author, Book_Category, Completion_Percent, ReadTogether, ReviewCount, Keyword, AudioBook]
Index: []

In [12]:
df_book["Keyword"].unique()

array([nan, '경제입문', '선물하기좋은책', '브런치수상작', '밀리인기도서50', '예술', '문가영추천도서', '술',
       '귀여운', '실내활동', '밀리독점', '내년준비', '갓생', '빵', '야외활동', '독서법', '시리즈',
       '직업의세계', '영앤리치', '챗GPT', '커피', '4050추천', '과학자', '심리에세이', '시간여행',
       '인간관계', '하버드추천도서', '필사추천도서', '블랙코미디', '무서운', '성장소설', '국내여행',
       '휴머니즘', '동네책방추천', '우주과학', '세계음식', '결혼', '어린이를위한', '여성주인공', '글쓰기',
       '덕질', '다이어트', '빌게이츠추천도서', '부커상', '뇌과학', '울고싶을때'], dtype=object)

### Drop "Keyword" Column

In [13]:
# Drop the 'Keyword' column
df_book = df_book.drop(columns=['Keyword'])

df_book

,Book_Name,Book_Author,Book_Category,Completion_Percent,ReadTogether,ReviewCount,AudioBook
0,"어린 왕자, 후쿠시마 이후",변홍철,에세이,NaN,2개,0,X
1,경제지표를 읽는 시간,빈센트(김두언),경제경영,완독할 확률 49%,"1,300개",4개,X
2,거대한 충격 이후의 세계,서영민,경제경영,완독할 확률 65%,378개,3개,X
3,노화의 재설계,모건 레빈 지음 / 이한음 옮김,인문,완독할 확률 43%,473개,3개,X
4,근대의 아틀리에,김영동,인문,NaN,9개,0,X
...,...,...,...,...,...,...,...
12711,다음 생엔 돌이 되고 싶다.,강다희,에세이,NaN,3개,0,X
12712,배터리 다이제스트 TOP9,선우 준,과학,NaN,5개,0,X
12713,배터리 다이제스트 TOP10,선우 준,과학,NaN,5개,0,X
12714,평신도 및 목회자를 위한 다니엘서 Q&A,우슬초,종교,NaN,3개,0,X
12715,나로 돌아가는 여행,곽나원,에세이,NaN,4개,0,X

## Integration Series books and deleting useless words about Book_Name

In [14]:
import pandas as pd
import re

def delete_rows_containing_text(df, column_name, texts_to_remove):
    for text in texts_to_remove:
        df = df[~df[column_name].str.contains(text, na=False, case=False)]

    return df

texts_to_remove = ['종료 D', '미서비스']
df_book = delete_rows_containing_text(df_book, 'Book_Name', texts_to_remove)


def delete_rows_by_conditions(df, conditions1, condition2):
    for condition1 in conditions1:
        df = df[~((df['Book_Name'].str.contains(condition1, na=False, case=False)) & 
                 (df['Book_Category'] == condition2))]

    return df

condition1 = ['기출', '모의고사','EBS']
condition2 = '자기계발'

df_book = delete_rows_by_conditions(df_book, condition1, condition2)

def identify_series_name(book_title, num_words=3):
    words = book_title.split()
    return ' '.join(words[:num_words]) if len(words) >= num_words else book_title

def integrate_series_data(data):
    data['Book_Name'] = data['Book_Name'].str.replace(r'\(\w+\)', '').str.replace(r'\d+권|\d+부|\d+화|\(완결\)|\(완료\)', '',regex=True)

    data['Series_Name'] = data['Book_Name'].apply(lambda x: identify_series_name(x))

    def extract_number(text):
        numbers = re.findall(r'\d+', str(text))
        return int(numbers[0]) if numbers else 0

    data['Completion_Percent'] = data['Completion_Percent'].apply(extract_number)
    data['ReadTogether'] = data['ReadTogether'].apply(extract_number)
    data['ReviewCount'] = data['ReviewCount'].apply(extract_number)

    grouped_data = data.groupby(['Series_Name', 'Book_Author', 'AudioBook'])

    data['Completion_Percent'] = grouped_data['Completion_Percent'].transform('mean').round()
    data['ReadTogether'] = grouped_data['ReadTogether'].transform('max')
    data['ReviewCount'] = grouped_data['ReviewCount'].transform('max')

    return data.drop_duplicates(subset=['Series_Name', 'Book_Author', 'Book_Category', 'Completion_Percent', 'ReadTogether', 'ReviewCount','AudioBook'])


df_book = integrate_series_data(df_book)

/var/folders/0c/33pbnmq11qd14nw6fg49k7sr0000gn/T/ipykernel_34227/1337569095.py:37: FutureWarning: The default value of regex will change from True to False in a future version.
  data['Book_Name'] = data['Book_Name'].str.replace(r'\(\w+\)', '').str.replace(r'\d+권|\d+부|\d+화|\(완결\)|\(완료\)', '',regex=True)

In [15]:
df_book

,Book_Name,Book_Author,Book_Category,Completion_Percent,ReadTogether,ReviewCount,AudioBook,Series_Name
0,"어린 왕자, 후쿠시마 이후",변홍철,에세이,0.0,2,0,X,"어린 왕자, 후쿠시마"
1,경제지표를 읽는 시간,빈센트(김두언),경제경영,49.0,1,4,X,경제지표를 읽는 시간
2,거대한 충격 이후의 세계,서영민,경제경영,65.0,378,3,X,거대한 충격 이후의
3,노화의 재설계,모건 레빈 지음 / 이한음 옮김,인문,43.0,473,3,X,노화의 재설계
4,근대의 아틀리에,김영동,인문,0.0,9,0,X,근대의 아틀리에
...,...,...,...,...,...,...,...,...
12709,150세에도 뛸 거야! 2편,유왕규,과학,0.0,1,0,X,150세에도 뛸 거야!
12711,다음 생엔 돌이 되고 싶다.,강다희,에세이,0.0,3,0,X,다음 생엔 돌이
12712,배터리 다이제스트 TOP9,선우 준,과학,0.0,5,0,X,배터리 다이제스트 TOP9
12713,배터리 다이제스트 TOP10,선우 준,과학,0.0,5,0,X,배터리 다이제스트 TOP10
12715,나로 돌아가는 여행,곽나원,에세이,0.0,4,0,X,나로 돌아가는 여행

### Bookdata to CSV

In [17]:
df_book.to_csv('all_book_preprocessing.csv', index=False)

## Review Data Preprocessing

In [18]:
df_review = df_review.dropna(subset=['Review_Text'])

df_review['Review_Text'] = df_review['Review_Text'].apply(lambda x: ' '.join([word for word in str(x).split() if word.isalpha()]))

df_review

,Nickname,Review_Text,Book_Name
0,그냥 대충 살기로 했다,내 고추가 필요할 때 잘 달리기 위해서는 평소에 내가 잘 달려야,남자는 어떻게 일어서는가
1,드로니,성기능과 건강은 건강에 왕도는 꾸준한 자기관리가,남자는 어떻게 일어서는가
2,연신내불닭발,역시,남자는 어떻게 일어서는가
3,유명한 개척자_252881,상대의 말만 듣지말고 상대를 들어보자 말의 한계 어휘부족 부적합한 제스처집중치말기,왜 욱하세요?
4,yyerin,사람이 무례한 사람,왜 욱하세요?
...,...,...,...
22000,비범한 아티스트_792651,재미있네요,종료 D-5\n \n 지옥연가
22001,꼼꼼한 개척자_609322,근데 왜 언니일을두고계속남주탓하지,종료 D-5\n \n 지옥연가
22002,후비적 후비적-,프롤로그는 임팩트가 있고 호기심을 자극해야 읽게 되는데 읽고싶은 요소가 읽덮,종료 D-5\n \n 지옥연가
22003,안개꽃7,,종료 D-5\n \n 지옥연가
22004,꼼꼼한 개척자_609322,아니,종료 D-5\n \n 지옥연가

In [19]:
nickname_review_count = df_review.groupby('Nickname')['Review_Text'].count()

sorted_nickname_review_count = nickname_review_count.sort_values(ascending=False)

nickname_review_count_10_or_more = sorted_nickname_review_count[sorted_nickname_review_count >= 1]

nickname_review_count_10_or_more

Nickname
철무정검               134
후비적 후비적-            79
책읽는스텔라루             74
새로운 컨설턴트_248165     70
파이리22               63
                  ...
똑똑한 작가_478265        1
똑똑한 작가_910511        1
똑똑한 주인공_234136       1
똑똑한 주인공_374460       1
힝히리힝                 1
Name: Review_Text, Length: 11081, dtype: int64

### load the data,"all_review_labeled_bi.csv" and re-Preprocessing

In [21]:
df_review = pd.read_csv("all_review_labeled_bi.csv", index_col=0)

In [22]:
df_review = df_review.dropna(subset=['Book_Name'])

### Delete Row with Useless Words

In [23]:
######################## 재구매 방지용 없애는 작업
# 필터링할 키워드 리스트
keywords = ["재독서방지", "재구독 방지", '재구매방지', '재열람방지','재구매 방지', '재구독방지용', '재구매 방지용', '재대여방지', '재구독방지']

# 각 키워드에 대해 str.contains를 사용하고 결과들을 OR 연산으로 결합
filter_condition = df_review['Review_Text'].str.contains(keywords[0])
for keyword in keywords[1:]:
    filter_condition |= df_review['Review_Text'].str.contains(keyword)

# 조건에 해당하지 않는 행들을 선택
df_review = df_review[~filter_condition]

In [24]:
df_review

,Nickname,Review_Text,Book_Name,Label
1,그냥 대충 살기로 했다,내 고추가 필요할 때 잘 달리기 위해서는 평소에 내가 잘 달려야 한다.,남자는 어떻게 일어서는가,1
2,드로니,성기능과 건강은 연결되어있다. 건강에 왕도는 없다. 꾸준한 자기관리가 답이다.,남자는 어떻게 일어서는가,1
3,연신내불닭발,역시 달리기?,남자는 어떻게 일어서는가,1
4,유명한 개척자_252881,상대의 말만 듣지말고 상대를 들어보자 말의 한계 어휘부족 부적합한 제스처집중치말기,왜 욱하세요?,0
5,yyerin,"욱""하는 사람이 무례한 사람",왜 욱하세요?,0
...,...,...,...,...
22001,비범한 아티스트_792651,재미있네요,종료 D-5\n \n 지옥연가,1
22002,꼼꼼한 개척자_609322,"그리고남주가못된넘인건맞는데,언니일은 남주탓은아니지않나? 근데 왜 언니일을두고계속남주탓하지",종료 D-5\n \n 지옥연가,0
22003,후비적 후비적-,프롤로그는 임팩트가 있고 호기심을 자극해야 읽게 되는데 읽고싶은 요소가 없음. 읽덮,종료 D-5\n \n 지옥연가,0
22004,안개꽃7,재밌어요~,종료 D-5\n \n 지옥연가,1
22005,꼼꼼한 개척자_609322,재밌는데.. 아니 여주언니죽었다고하지않았나요?책여러군데에죽었다고나오든데..뭐지ㅡㅡ;;,종료 D-5\n \n 지옥연가,1

### Identify Preprocessing about Book Name of Review Data with Book Data
> Integration about Series Book in "Book Name" Column of Review Data

> Delete "종료 D" , "미서비스" text in "Book Name"

In [25]:
#book 데이터 전처리한 것 기반으로 실행
texts_to_remove = ['종료 D', '미서비스']
df_review = delete_rows_containing_text(df_review, 'Book_Name', texts_to_remove)

def identify_series_name(book_title, num_words=3):
    words = book_title.split()
    return ' '.join(words[:num_words]) if len(words) >= num_words else book_title

def integrate_series_data(data):
    data['Clean_Book_Name'] = data['Book_Name'].str.replace(r'\(\w+\)', '').str.replace(r'\d+권|\d+부|\d+화|\(완결\)|\(완료\)', '', regex=True)

    data['Series_Name'] = data['Clean_Book_Name'].apply(lambda x: identify_series_name(x))

    first_book_name_by_series = data.groupby('Series_Name')['Book_Name'].first().to_dict()

    data['Book_Name'] = data['Series_Name'].map(first_book_name_by_series)

    return data.drop('Clean_Book_Name', axis=1)

df_review = integrate_series_data(df_review)

/var/folders/0c/33pbnmq11qd14nw6fg49k7sr0000gn/T/ipykernel_34227/3236587585.py:13: FutureWarning: The default value of regex will change from True to False in a future version.
  data['Clean_Book_Name'] = data['Book_Name'].str.replace(r'\(\w+\)', '').str.replace(r'\d+권|\d+부|\d+화|\(완결\)|\(완료\)', '', regex=True)

In [27]:
df_review

,Nickname,Review_Text,Book_Name,Label,Series_Name
1,그냥 대충 살기로 했다,내 고추가 필요할 때 잘 달리기 위해서는 평소에 내가 잘 달려야 한다.,남자는 어떻게 일어서는가,1,남자는 어떻게 일어서는가
2,드로니,성기능과 건강은 연결되어있다. 건강에 왕도는 없다. 꾸준한 자기관리가 답이다.,남자는 어떻게 일어서는가,1,남자는 어떻게 일어서는가
3,연신내불닭발,역시 달리기?,남자는 어떻게 일어서는가,1,남자는 어떻게 일어서는가
4,유명한 개척자_252881,상대의 말만 듣지말고 상대를 들어보자 말의 한계 어휘부족 부적합한 제스처집중치말기,왜 욱하세요?,0,왜 욱하세요?
5,yyerin,"욱""하는 사람이 무례한 사람",왜 욱하세요?,0,왜 욱하세요?
...,...,...,...,...,...
21911,꿈이현실,주린이들이 꼭 읽어봐야 할 책 이네요. 오랜만에 주식관련 책을 재미있게 잘 읽었습니다.,세력주 투자 기술,1,세력주 투자 기술
21912,지미오양,주식 잘 모르겠으면 이것부터 읽어보시라,세력주 투자 기술,1,세력주 투자 기술
21913,플러스비,장난이 너무 심한거 아니요?,세력주 투자 기술,0,세력주 투자 기술
21914,ADHD 직장인의 일생다반사,투자에 공부에 대한 마음에 다시끔 불을 지펴준 책,세력주 투자 기술,1,세력주 투자 기술
21915,kosmes2112029,도움이 많이되는 실전 노하우를 알려주는 좋은책,세력주 투자 기술,1,세력주 투자 기술

### Review Data to CSV

In [28]:
df_review.to_csv('all_review_preprocessing.csv', index=False)